apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: anthropic
  namespace: ai
spec:
  type: AI
  ai:
    llm:
      anthropic:
        model: "claude-3-5-sonnet-latest"
        authToken:
          kind: SecretRef
