apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: anthropic
  namespace: ai
spec:
  type: AI
  ai:
    llm:
      provider:
        openai:
          model: "anthropic-claude-sonnet-4-20250514"
          authToken:
            kind: Secret
            secretRef:
              name: anthropic-api-key
              key: ANTHROPIC_API_KEY
