---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend.yaml
  - models/claude-3-5-sonnet.yaml
  - models/claude-4-sonnet.yaml
  - http-route.yaml
generators:
  - secrets-generator.yaml
