apiVersion: ENC[AES256_GCM,data:IEU=,iv:bNwmN8CQV8YXXNKZ7e77kcJK/67cJaBeCjptjv+xLLE=,tag:reeAbL/AEH5XrASVFFw/Zg==,type:str]
kind: ENC[AES256_GCM,data:5aGNmWLQ,iv:eEYO/Hs3hrIdX37N5TQfoJAgVg4ZLm7Gj6QgvsGYgJM=,tag:7fbiLar1MWJ3nm54GTGHqw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2B8782jdGwgsABpdj6iFNTw=,iv:ALINN2eV8y3bDYKvLYxKBbb4FLwQ0ho6WmkbSJOyCQY=,tag:zOm2ic8kb/e/8lkqkZt5/g==,type:str]
    namespace: ENC[AES256_GCM,data:C5w=,iv:nvJwbZ+b6hJgtk2YPzzP74JN8l1DpYWIV83GnNtkC0c=,tag:te9L2lZqhIL49vZQhvbuzg==,type:str]
type: ENC[AES256_GCM,data:c6Xz/V2G,iv:kU39SyrSs7X/wgQhGX9dl01/A1eRhW8PNxEwdEwo1qs=,tag:nq2mt793qEWTMRm0ZOIAyQ==,type:str]
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:6k3jKdwyJmxPE3FMtuDyrGruMJLO7DRgvP4PA9/3ONGF2nqCefm6uQJ64WVMv4z2gtZFOgq0F6ChxIFD3iP4Kynqr16QMlnz9kaNKpO/Kq4V6LV4x/j3s540PshxlZlssJXDqlp5QTVH5FCj,iv:ASXvLo/kIu15qRjAUJKGX4M9UbWlSREWbPgDbfxqd8g=,tag:LdO25JUwFMjar0KSwq+TBQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2025-11-25T17:10:29Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAHJ31qqqqTm6OYXz26LZALsAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+lUuwisvKBonnWbNAgEQgDsp/hLceeus8DXfTs3SLpZS79yWb94CCUT4mW3efyBQVSfA/O6RtiZG7Ou/Fsjh+jRqrZNJUN3vWpWwzQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-25T17:10:29Z"
    mac: ENC[AES256_GCM,data:CbWDS+1wHcmfPWWBwDIYRwUhibjNUzzHUyXejFnyjCr0WbcD2IKdX7YLYa8Wd6rq8De70xocAQ6A2E7jsLP2KgoQUP5mGO1sSzkEXaIUMGGJ1wUhQUbjdvDege1aeF9J1zGmVHCWnlMkMGs/uvtxc2rPwdnJY9Nf0YfKyNJ2CG8=,iv:eRIZBzA0F+eEWeilByjWbyBiGmCVbbPdEKK1jehvh/M=,tag:djECjJsPyKdaIiaZupcYQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
