apiVersion: ENC[AES256_GCM,data:O9s=,iv:RiWPmbAZZYYZo+ZFtW9Q7V0AixTU7UmRkpKvUUrWk30=,tag:u94V5PCygwLJu4YxjKPoCA==,type:str]
kind: ENC[AES256_GCM,data:JKo75pRY,iv:J+UABobgI/i9MM1fJfSpvkBtdVEuz/F94g63MvxoRzg=,tag:mLhq3oqJPTDnGdI42Pj/uw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dU/ArsozK9rUikrKGL0sKcI=,iv:6iktpkdEor67CXG1nl9CvkVY2nafisPBM8xGq/JxqDg=,tag:GaX26XmjDtEiTfSmDeFTeQ==,type:str]
    namespace: ENC[AES256_GCM,data:rP8=,iv:nZh4+wzR6Ei7g6bRcZVgKgK/v0f8zwc6gcu9U1WE4zU=,tag:r6th7uxpB451XF/tlAmESA==,type:str]
type: ENC[AES256_GCM,data:yBKqgula,iv:BOGvtkFzizPqs73zHlOiME6PXfWfEDXVVHlusePpSZo=,tag:3KhdQIqWA/RY/IiMr0QYzw==,type:str]
stringData:
    Authorization: ENC[AES256_GCM,data:orRG2xqADmRHGob65Fj1fwdVFpuaAhqGbKzqj5nefoQDbLSUJNhS9wCgnb+YbWBHYuA7sZbIbNUiDPo1mNZLlozs2iS0+J596mTIV8bf81NoZKZkvpJ3EAw/nPsxxCxa0pK2UfErFWG8guQn,iv:k6X4g+8l0ze61+yxDwMeLAqV3OaM1qe6D0RIz7k4AMA=,tag:kF6YZKyaU9FFSHV9lU5WtA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2025-12-20T17:00:27Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAH5K7ybeLXFxQgYY0Wr8d/TAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMhParmT8J767D3KQpAgEQgDt6bk7fxBx/bEoPHwQj2JZUEA8G7+9pQWmIfrlhW1bQZDNt9bk+iXv8mgsqz1vc+ymOcPsYr4Wi1/FqnQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-20T17:00:28Z"
    mac: ENC[AES256_GCM,data:bghGmeENMX5ecIS298lq4utKb/2tNRcjNTPAKeYeLQP/sgaxsIYegQB7Izx9vKa9WD/VkMZeHNoRx2lX1Ho+lthfnm8mT2fbXhfzCfwi1rw5B81dWEEn30S0UZy3sH9mLt2YwVYd5PHC8wKSO0w/0YziKACUYgWJD8LZPNnqglQ=,iv:OhIgiqtyL+3RGG1olWGOxbkwbMPtUsaie6h8OJDe/XA=,tag:KDnmFUIZGXn4SwXn7GepMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
