---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-dns-issuer
spec:
  acme:
    email: ${EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-dns-key
    solvers:
      - dns01:
          cloudflare:
            email: ${EMAIL}
            apiKeySecretRef:
              name: cloudflare-api-key-secret
              key: CLOUDFLARE_API_KEY
        selector:
          dnsZones: ["${CLOUDFLARE_DOMAIN}"]
