---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: external-cluster-issuer
  namespace: cert-manager
spec:
  acme:
    email: ${EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: external-cloudflare-issuer-key
    solvers:
      - dns01:
          cloudflare:
            email: ${EMAIL}
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: CLOUDFLARE_API_TOKEN
