apiVersion: ENC[AES256_GCM,data:eOk=,iv:RRIjlJyEmkJvHkI9owW0JobThVn3yAk/KaqgUWHEm9M=,tag:7TPmk7gbq8pluKLmSq3/4g==,type:str]
kind: ENC[AES256_GCM,data:J27rDyCL,iv:OoDEE6KPwxourNzeuHEKZDneMZGnd+kCMQOFgX+vpeI=,tag:IqrZzqBhfRrs92SYkpiA9g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:l6aprUUDZl07I5ZIXFr9Z+ljY6dRtYioew==,iv:D5LeqjnDxHv7a/9bS0r9RI4lRDZRudDlrciNKqytaHw=,tag:9GuFXFt3XpGmCiIgGWO2HQ==,type:str]
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: ENC[AES256_GCM,data:72SL5Q==,iv:Mz7Sxv/2mWnc/gZ0buHhNlHSFz4bvjq9Ec4e6ae1lKE=,tag:GCGeS1XnuGtzDj59i4JSVw==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ENC[AES256_GCM,data:PSDROg==,iv:fkPbpV+sKrYPSYNgKas3Zt6t7KdN7TqbcS2+0/muVpA=,tag:pMvibZAcYBT0CEz/7qB+Sg==,type:str]
type: ENC[AES256_GCM,data:n55CeoHu,iv:1LVjayHER5DO/abujchdWmH1SHem0wrzWu5Gotan+Ho=,tag:cLWP+9cTxtx2q1Qtyyf4Bw==,type:str]
data:
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:n0dk3rD2fWol7S/dveTf2SCU7ARXe4f59TwYDCEafUEXiYsmjA==,iv:3Db5m71+/wjygrawv5D77RSkWDHQe2YoQskTnHHv8SY=,tag:ALHwAhrZf2AsbtgWgCFWrw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2025-12-16T21:32:38Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAGRTAx3V0dABBsHfN6e6+PEAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMIczm4PSOGI+mb1a3AgEQgDs01oS2Q6f4vHLB/9lKLCqqVxj43Ynh5Y85os76xERAUDUl6pRtce6tak+fXP4BKiwxbU2bD1Vpl9GjAg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-16T21:32:38Z"
    mac: ENC[AES256_GCM,data:Ql9z38Coa61kD7PZlm0sZTqRhF31YTFQJKAc7PzD0hFa5LV569zunWniFLstwTsflR3QaPXhIgb/pF+hYz8B9kKUici1eaIuHKOYCPJYr8xnwCHQ3k+XS/UD/ikfoAPYPZ7l2WiQUpLqDjgXXuZ+FJnnJjblwvPIlDBog+8uPy0=,iv:x+yK0hTs6zlQB1yIy6Kg9kJnYE/SNQ70MfsJZL5DBEo=,tag:j7xKJeIBPxkpsyu08C5uHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
