apiVersion: ENC[AES256_GCM,data:Kec=,iv:4whnUSnOcjdKz0xm5y2/W7b4CtVOi09uEhgaFhyU+h0=,tag:aM5M6GZBaygynPKVRqVHBA==,type:str]
kind: ENC[AES256_GCM,data:8YJfC9GZ,iv:XoWQY5Nx1UrRr5BL74QyPmS7I3mikiVXj+b7ir0kYP8=,tag:R/OdMm7epUrsM8uRtF5QtQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Xe8B/ZpWCQQy/zKiglm695tEmro89DgltA==,iv:5JtAMUqIkZ+wmwuSEi+cuLieG3hgHBeGtSdlMS7GKvY=,tag:AIme5eKCYNzkdiNrsFJKNA==,type:str]
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: ENC[AES256_GCM,data:xbt2cQ==,iv:kPAaUEuPl4rXd4NSc6iyV8tu5V660eZ0QWuDsrHSvUY=,tag:PbLA0zMB0P5OL4Q6DvpPHQ==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ENC[AES256_GCM,data:idh1Uw==,iv:jhdv0Ajl9wlaDLUuDMm2dtNWKLuzoOsnzgB43WM6VYs=,tag:luB/h0cBvGmk7qVcu9A+yA==,type:str]
type: ENC[AES256_GCM,data:nj7/Bo2o,iv:Okw3iAkeK1nypXFCtqOoRgr28xmgyFg8oRv3MkMYSrc=,tag:M9ZURPXPCgBSj7uGM67w5g==,type:str]
stringData:
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:FNokSVDZPc9FnTXg4uVnbIhJF3Qs5VG/GT5m8rLkamIw2k3XjA==,iv:agpWCLa7QuzxTwM4jSD6o0TT/TxSTfeG536/X3hSX9E=,tag:7yh8ojtrxBnsziOIaVz9og==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2025-12-21T16:25:37Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAEejvtycKYFCyVFoNkwTYxbAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMyVazNn2aWmQ8ZGIRAgEQgDs74uHtHOFJitnsrSvdJwHBe/1gR6CIv7GxxrOAV2wSvWqWS1p3X0JgqD+ta2kNv72xlhxuWPd6Xw/bHg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-21T16:25:37Z"
    mac: ENC[AES256_GCM,data:PcYQcew9j4aM60sxJM9jgrPOwKN0uTgo5KxX2jDu6Ro73AsOZ6kBT8iJEE336s4TWALEq0xwiWpCI6dws67b5z0m0G5c/07o3L+6jRB6jwixsT1s23vBLftxv9WLmaBR9bFkr4j9J+7PHdqZiZGw1zCKwzEix2x8eBjyE74zaCg=,iv:96ZBTBaUMN1VHeaQtbXDTrlGMmUlRaSLcovpfcbym44=,tag:iFUN9pFdYMK0iNxaXUoPgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
