apiVersion: ENC[AES256_GCM,data:HGs=,iv:YnPp/wvMi21JhaRazx0plwnqBxickmqId8I8ytmgCu8=,tag:8SgNz5nZM1aOinGPX7Hokg==,type:str]
kind: ENC[AES256_GCM,data:pSOkOPmW,iv:oQGxBwb5+RrzPgJVVfAZgYNaZblEBEXJPPSnyH72qMA=,tag:83XGIYHGz4xu6CYUMj5b3A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cRWQdHzQyGKKVEsfFwvB7HWITwlJWQzYug==,iv:CcGwzchIMGMtXFXItKMElMAffIlagKHhR5BaP1X3bQs=,tag:AMey5HYCiQQnFaK51gfQ1Q==,type:str]
    namespace: ENC[AES256_GCM,data:mkDJQXmzZbygB/Hw,iv:ljVEjl0jDBEks4EY8IB2Ej07koZ2myo/hYGVWH/iqrw=,tag:NU4ty1onJKZiYLsB/gHBgA==,type:str]
type: ENC[AES256_GCM,data:VdqY3u/4,iv:taBtLSO91Zu13EBHdI0DKh2RU3ZGWtJmqOKMWCHA4Y0=,tag:tFfkNv7j2gPL3yMu7vdZRA==,type:str]
data:
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:/e5AnF3+yJZXciH++fOfUz96worCddFzagIyF9faQ4JYrrTOvHRtI+FW7Ep8URvHUh4ftQ==,iv:Sj7Z8YOMzU8ghv8RJ1NIjhSdiiv9LnNDep1ZWPATlf8=,tag:S2K+M6IfS4/VThKsIzHiKA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2025-11-24T20:18:53Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAFfhXInSlRuT6dxV6RnvI8DAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMYeEjBrEIKjhT1HAgAgEQgDtU6WQzklxl09i3tG1QlUjQGqzf+8Jiv/V7wpDoeyT4TZI/fxe+sXR6dWdYM174TVb7Zxw4nQWNW8QLRw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-24T20:18:53Z"
    mac: ENC[AES256_GCM,data:11vHaFvZRsnfGG91G91WEIxEpE6SWooCOiD9w4IYICvEaaJFN0CeYB4AUZZtFX5m0VvJJ00bkRgMWIWIV7M/AHf0nO6Aw3NCwgyJOvNeHY2GE7FOIW7BMweaB/G7KXmfnHMKvWQTlexIx/thcmUKYWzbIJBSE2nvOs8JUcwK8bQ=,iv:ipHSw4QsEUozLLFurfrwvJ0Dj5UIcFeeT/vJEYBCF28=,tag:U/7pvutEX9MoLMKxa49tQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
