---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: n8n-external-route
  namespace: automation
  annotations:
    external-dns.alpha.kubernetes.io/exclude: "true"
spec:
  parentRefs:
    - name: homelab-external-gateway
      namespace: kube-system
  hostnames:
    - "n8n.teaglebuilt.tech"
  rules:
    - backendRefs:
        - name: n8n-service
          port: 443
