---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: homelab-external-gateway
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: homelab.external
spec:
  gatewayClassName: cilium
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "homelab.external"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: external-cloudflare-tls
