---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-certificate
  namespace: kube-system
spec:
  secretName: external-cloudflare-tls
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - "{{ .Values.external.domain }}"
    - "*.{{ .Values.external.domain }}"
  issuerRef:
    name: cloudflare-dns-issuer
    kind: ClusterIssuer
