---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ip-pool.yaml
  - announcement.yaml
configMapGenerator:
  - name: cilium-base-values
    files:
      - values.yaml
      - clustermesh-values.yaml
generatorOptions:
  disableNameSuffixHash: true
