---
apiVersion: kagent.dev/v1alpha1
kind: ModelConfig
metadata:
  name: anthropic-claude-4-sonnet-20250514
spec:
  anthropic: {}
  apiKeySecretKey: ANTHROPIC_API_KEY
  apiKeySecretRef: anthropic-api-key
  model: claude-sonnet-4-20250514
  provider: Anthropic
