---
apiVersion: v2
name: homelab-gateway
description: Helm Chart for homelab gateway
type: application
version: '1.0.0'
appVersion: 'v1.0.0'
dependencies:
  - name: cloudflare-tunnel
    repository: https://cloudflare.github.io/helm-charts
    version: 0.3.2
  - name: kgateway-crds
    version: v2.1.0-main
    repository: oci://cr.kgateway.dev/kgateway-dev/charts
  - name: kgateway
    version: v2.1.0-main
    repository: oci://cr.kgateway.dev/kgateway-dev/charts
