---
kgateway-crds:
  controller:
    image:
      pullPolicy: Always

kgateway:
  agentgateway:
    enabled: true

  controller:
    image:
      pullPolicy: Always
    deployment:
      extraArgs:
        - --zap-log-level=info
