---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: gpu.rules
  namespace: kube-system
spec:
  groups:
    - name: dcgm-exporter
      rules:
        - alert: HighGpuUsage
          expr: |
            rate(DCGM_FI_DEV_GPU_UTIL[15m]) > 0.85
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "High GPU usage on node {{ $labels.Hostname }} for 15 minutes"
    - name: vllm.latency.rule
      rules:
        - alert: vLLMLatency
          expr: max_over_time(time_per_output_token_seconds}[5m]) >= 0.3       1
          labels:
            severity: critical
            app: my-model
          annotations:
            message: Latency of vLLM is too high.
