---
apiVersion: v1
kind: Service
metadata:
  name: openedai-speech
  namespace: ai
  labels:
    app: openedai-speech
    component: tts
spec:
  type: ClusterIP
  selector:
    app: openedai-speech
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
