services:
  paperless-nxg:
    ...

  paperless-ai:
    image: clusterzx/paperless-ai:latest
    restart: always
    ports:
      - 3003:3000
    volumes:
      - /mnt/local/media/paperless:/app/data
    networks:
      - proxy

networks:
  proxy:
    external: true
