---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus
helmCharts:
  - name: parca
    repo: https://parca-dev.github.io/helm-charts
    version: 4.19.0
    namespace: observability
    releaseName: parca
    valuesInline:
      nodeSelector:
        kubernetes.io/hostname: mlops-work-00
      agent:
        serviceMonitor:
          enabled: true
