---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  cluster: administration
  cilium.io/cluster: administration
bases:
  - ../../base
configMapGenerator:
  - name: cilium-administration-values
    files:
      - values.yaml
    behavior: merge
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cilium-base-values
      namespace: kube-system
    data:
      cluster-name: administration
      cluster-id: "2"
generatorOptions:
  disableNameSuffixHash: true
