---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  cluster: mlops
  cilium.io/cluster: mlops
bases:
  - ../../base
configMapGenerator:
  - name: cilium-mlops-values
    files:
      - values.yaml
    behavior: merge
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cilium-base-values
      namespace: kube-system
    data:
      cluster-name: mlops
      cluster-id: "1"
generatorOptions:
  disableNameSuffixHash: true
