apiVersion: ENC[AES256_GCM,data:zL4=,iv:3hLZ9PLkNP7VMHLn5dRHQVL19gmsDhIJKJhkwrjVbF8=,tag:0dkHNJp/t9CVrQGjnuIUIA==,type:str]
kind: ENC[AES256_GCM,data:xVPFN2xP,iv:QBXpbX3VPibS4iqNmxEMpHDsJKLf77pPK5fE4dgT2mw=,tag:x8ulKQvxvBLn/PN0Tn47ng==,type:str]
metadata:
    name: ENC[AES256_GCM,data:w7ytKcdjtx48vJ9vhlG2NRroWI1z,iv:w24z5JebwgNUO1vdJSxCLXmBZ64PYLvz3+xvpSUjN5M=,tag:EW5zoIwfhiUg9hSDCd4Hdw==,type:str]
    namespace: ENC[AES256_GCM,data:oAk=,iv:b1VTvPh6++/VXg39CXHnYsi50VuOEnIjQCI3Byt3EMY=,tag:DeEsoFQSLqXxCIZib8IOfA==,type:str]
type: ENC[AES256_GCM,data:bfxQcxUV,iv:qDeY9XKWkcsYyEpfcOxItd5xL1yq/BHSzGL6Gr5G/sE=,tag:HT8zKTk3NC4TDY65SCPqfA==,type:str]
stringData:
    Authorization: ENC[AES256_GCM,data:Ef5lSiUWSMUYYvA2Ses68zwGAKFlCYDEBmDoR77lhnIUjcoYW9UaDDUCTvxORl0mO0LPf2uGfbKZN9BsRDIabRtcGOXOY1Yvx+3ODsJ9y8jHRMgwEzrlfBWfI/qi4kiTKhPLv5WtM2aHoWv5FXofPuPn50xqonrlmxM98MnCutkQmR4Ao3cBapsO1vBitstCC3bz10CynD60wYHl40nGadJ/ZU0=,iv:pGNlhoJBML0Sq672Gau6+4bokvHmf6BrYTUGzgjnvs8=,tag:bJsbyCdu75KGwXrR1OHmYg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2025-12-20T17:02:06Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAGO/QgMSOUBHObeIW+W0MaiAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVGa9yQcehRtSGLeRAgEQgDsCtQVhBIa6dW6xqmEOmTJvDLaCuIEBUh9//y2CLfVYkDEfNGmZKSehzOFyXA2gtvUPKxajS//qMMRi7g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-20T17:02:06Z"
    mac: ENC[AES256_GCM,data:W62JVa6mCycaNqXJkzB7hh3AaDTNcWVNq4KJLAihiMjtI9E7xlSyrbS3k3BJI0Ik28k5wPBI36i/ZQjbtTpjtmkhPywgbOilxIaYg2Xp4dn6jbIpySHyzhy1TqVbEiOPzrrOdkSvo198E79FQmNBB5sBTYFLmHiQEryylbnYdKo=,iv:xikLhYcQDxW7ib8kG0gnwzT1TDHgLtt5Sx0C0t0uch8=,tag:LrLPI3nSR0DR7tkcS2NbYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
